Repository openfisca/tutorial, pull requests merged in 2018-04, with the labels that each got.

#29 Rename reforms to fit documentation
  CHANGELOG.md
  python/A_creer_reforme_parametrique.py
  python/B_calculer_avec_reforme_parametrique.py
  python/C_calculer_avec_reforme_structurelle.py
  python/D_investiguer_avec_les_situations_types.py
  python/reforme_parametrique.py
  python/reforme_structurelle.py
Labels: flow:support:doing

#30 Foire Aux Questions
  CHANGELOG.md
  README.md
Labels: flow:team:doing

#31 Normalise comments
  CHANGELOG.md
  python/A_creer_reforme_parametrique.py
  python/B_calculer_avec_reforme_parametrique.py
  python/C_calculer_avec_reforme_structurelle.py
  python/D_investiguer_avec_les_situations_types.py
  python/exemples/gt_non_recours/framework.py
  python/exemples/gt_non_recours/framework_methods.py
  python/exemples/gt_non_recours/framework_no_reform/investiguer_achetypes.py
  python/exemples/gt_non_recours/reformes/reforme_test.py
  python/reforme_parametrique.py
  python/reforme_structurelle.py
Labels: flow:team:doing, kind:documentation

#33 Modéliser la réforme des AL 2019
  .gitignore
  CHANGELOG.md
  README.md
  exemples/__init__.py
  exemples/gt_non_recours/Makefile
  exemples/gt_non_recours/README.md
  exemples/gt_non_recours/__init__.py
  exemples/gt_non_recours/framework.py
  exemples/gt_non_recours/framework_methods.py
  exemples/gt_non_recours/img/rstudio_set_working_dir.png
  exemples/gt_non_recours/periods.py
  exemples/gt_non_recours/reformes/__init__.py
  exemples/gt_non_recours/reformes/reforme_al01M.py
  exemples/gt_non_recours/reformes/reforme_al03M.py
  exemples/gt_non_recours/reformes/reforme_al12M.py
  exemples/gt_non_recours/reformes/reforme_test.py
  exemples/gt_non_recours/requirements.txt
  exemples/gt_non_recours/resultats-levels.ods
  exemples/gt_non_recours/situations.py
  exemples/gt_non_recours/situations/README.md
  exemples/gt_non_recours/situations/celibataire_1-enfant_mes-aides-546b1ae4de0b44f86312e86f.json
  exemples/gt_non_recours/situations/celibataire_2_enfants_2000_mes-aides_5a70b9cd4b64656dc14d57c3.json
  exemples/gt_non_recours/situations/celibataire_aah_mes-aides_5a70bfe34b64656dc14d58a5.json
  exemples/gt_non_recours/situations/celibataire_handicap_567_mes-aides_5a70c1674b64656dc14d58d4.json
  exemples/gt_non_recours/situations/celibataire_handicap_700_mes-aides_5a70c0b64b64656dc14d58b9.json
  exemples/gt_non_recours/situations/celibataire_indep_15000_benef_mes-aides-5a70bc044b64656dc14d580c.json
  exemples/gt_non_recours/situations/celibataire_indep_24000_ca_mes-aides-5a70bcb04b64656dc14d582a.json
  exemples/gt_non_recours/situations/celibataire_indep_35000_ca_mes-aides_5a70bd554b64656dc14d5843.json
  exemples/gt_non_recours/situations/celibataire_retraite_1428_mes-aides_5a70be984b64656dc14d5878.json
  exemples/gt_non_recours/situations/celibataire_retraite_aspa_mes-aides_5a70bdfa4b64656dc14d585b.json
  exemples/gt_non_recours/situations/celibataire_sans_enfant_SMIC_mes-aides_5a6fa711c912826f01694169.json
  exemples/gt_non_recours/situations/changement_situation.json
  exemples/gt_non_recours/situations/couple_2_enfants_2303_mes-aides_5a70ba714b64656dc14d57cb.json
  exemples/gt_non_recours/situations/couple_2_enfants_revenues_variables.json
  exemples/gt_non_recours/situations/couple_2_enfants_revenus_stables_mes-aides_5a80cb3fd7e09f619d5e0ae3.json
  exemples/gt_non_recours/situations/couple_3_enfants_4000_mes-aides_5a70bb504b64656dc14d57eb.json
  exemples/gt_non_recours/situations/couple_retraite_3858_mes-aides_5a70bf3d4b64656dc14d5894.json
  exemples/gt_non_recours/situations/couple_retraite_revenus_variables.json
  exemples/gt_non_recours/situations/couple_retraite_stable_mes-aides_5a80c6fcd7e09f619d5e0aaf.json
  exemples/gt_non_recours/situations/couple_sans_enfant_4000_mes-aides_5a70b8254b64656dc14d577f.json
  exemples/gt_non_recours/situations/couple_sans_enfant_SMIC_mes-aides_5a70b8254b64656dc14d577f.json
  exemples/gt_non_recours/situations_test/bill_bob_janet.json
  exemples/gt_non_recours/vizu.R
  python/README.md
  python/exemples/gt_non_recours/README.md
  python/framework/__init__.py
  python/framework/framework.py
  python/framework/framework_methods.py
  python/framework/framework_no_reform/__init__.py
  python/framework/framework_no_reform/clean_mes_aides_situations.py
  python/framework/framework_no_reform/investiguer_achetypes.py
  python/framework/reformes/__init__.py
  python/framework/reformes/reforme_test.py
Labels: flow:team:doing
